import { ToolMeta } from '../types';

/**
 * Pre-audited, high-performance SEO Title mappings for all Zubware tools.
 * Rules applied for optimal Google Search performance:
 * 1. Target SERP character length: 45–65 characters (optimal display without truncation).
 * 2. High-intent primary keywords positioned early (e.g. "PDF to Word Converter", "Image Compressor", "ATS Resume Builder").
 * 3. Clear action verbs / benefit propositions ("Convert", "Compress", "Online Free", "Maker").
 * 4. Consistent, single brand suffix (`| Zubware`).
 * 5. Zero redundant brand repetition or duplicate words.
 */
export const TOOL_SEO_TITLES: Record<string, string> = {
  // --- Core & Image Tools ---
  'splitdrop': 'Image Splitter & Photo Merger — Zubware Online Free',
  'learning-licence-mock-test': 'Learning Licence Mock Test — RTO Exam Practice | Zubware',
  'background-remover': 'Background Remover — Free AI Image BG Remover | Zubware',
  'image-compressor': 'Image Compressor to 20KB, 50KB, 100KB, 200KB Free Online | Zubware',
  'image-converter': 'Image Converter — Convert JPG, PNG, WebP & GIF | Zubware',
  'image-resizer': 'Image Resizer — Resize Photos by Pixels or % | Zubware',
  'crop-image': 'Crop Image Online — Free Photo Cropper & Trimmer | Zubware',
  'rotate-image': 'Rotate Image Online — Flip & Turn Photos Free | Zubware',
  'flip-image': 'Flip Image Online — Mirror Photos Horizontally | Zubware',
  'image-watermark': 'Watermark Image — Add Text & Logo to Photos | Zubware',
  'blur-image': 'Blur Image Online — Blur Backgrounds & Faces Free | Zubware',
  'pixelate-image': 'Pixelate Image — Censor & Pixelate Photos Free | Zubware',
  'exif-remover': 'EXIF Remover — Strip Photo Metadata Privately | Zubware',
  'image-color-picker': 'Image Color Picker — Hex, RGB & Eyedropper | Zubware',
  'image-info-viewer': 'Image Info Viewer — Inspect Dimensions & EXIF | Zubware',
  'background-color-changer': 'Change Background Color — Replace Image BG Free | Zubware',
  'rounded-corners': 'Rounded Corner Generator — Round Photo Edges | Zubware',
  'image-border': 'Add Border to Image — Custom Color Frames Online | Zubware',
  'image-frame': 'Photo Frame Maker — Add Decorative Frames Online | Zubware',
  'image-collage': 'Photo Collage Maker — Combine Pictures Online | Zubware',
  'favicon-generator': 'Favicon Generator — Create .ico & App Icons Free | Zubware',
  'svg-optimizer': 'SVG Optimizer — Compress & Clean Vector SVGs | Zubware',
  'gif-maker': 'GIF Maker — Create Animated GIFs from Images | Zubware',
  'batch-image-converter': 'Batch Image Converter — Convert Multiple Photos | Zubware',
  'compression-comparison': 'Image Compression Comparison — Compare Quality | Zubware',
  'heic-to-jpg': 'HEIC to JPG Converter — Convert iPhone Photos | Zubware',
  'bulk-image-renamer-resizer': 'Bulk Image Resizer & Renamer — Batch Edit Free | Zubware',
  'passport-photo-maker': 'Passport Photo Maker — Free ID & Visa Photos | Zubware',
  'matching-parts-video-maker': 'Matching Parts Video Maker — Create Puzzle Shorts | Zubware',

  // --- Audio Tools ---
  'lofi-song-maker': 'Lofi Music Studio — Beat Maker & Ambient Synth | Zubware',
  'lofi-maker': 'Lofi Audio Maker — Slow & Filter Songs Online | Zubware',
  'slowed-and-reverb': 'Slowed & Reverb Generator — Chill Audio Effects | Zubware',

  // --- Business & PDF Tools ---
  'gst-invoice-generator': 'GST Invoice Generator — Free Tax Invoices PDF | Zubware',
  'pdf-merge': 'PDF Merge — Combine Multiple PDF Files Online | Zubware',
  'pdf-split': 'PDF Split — Extract & Separate PDF Pages Free | Zubware',
  'image-to-pdf': 'Image to PDF Converter — JPG & PNG to PDF Free | Zubware',
  'pdf-to-images': 'PDF to Image Converter — Convert PDF to JPG/PNG | Zubware',
  'rotate-pdf': 'Rotate PDF Online — Turn & Save PDF Pages Free | Zubware',
  'delete-pdf-pages': 'Delete PDF Pages — Remove Unwanted Pages Free | Zubware',
  'extract-pdf-pages': 'Extract PDF Pages — Split & Save Selected Pages | Zubware',
  'reorder-pdf-pages': 'Reorder PDF Pages — Rearrange & Sort Pages | Zubware',
  'pdf-watermark': 'Add Watermark to PDF — Stamp Text & Logos Free | Zubware',
  'protect-pdf': 'Protect PDF — Add Password & Encrypt PDF Online | Zubware',
  'unlock-pdf': 'Unlock PDF — Remove Passwords from PDF Files | Zubware',
  'pdf-metadata': 'PDF Metadata Editor — View & Edit PDF Info Free | Zubware',
  'qr-generator': 'Free QR Code Generator — Create Custom QR Codes | Zubware',

  // --- Career Tools ---
  'resume-builder': 'ATS Resume Builder — Free Professional CV Maker | Zubware',
  'ats-resume-checker': 'ATS Resume Checker — Optimize Your CV for Jobs | Zubware',
  'resume-score-analyzer': 'Resume Score Analyzer — Review ATS Compatibility | Zubware',
  'cover-letter-builder': 'Cover Letter Builder — Professional Templates | Zubware',
  'cover-letter-templates': 'Cover Letter Templates — Free Job Cover Letters | Zubware',
  'cv-builder': 'Free CV Maker — Create Professional Curriculum Vitae | Zubware',
  'resume-keyword-optimizer': 'Resume Keyword Optimizer — Match Job Descriptions | Zubware',
  'resume-template-gallery': 'Resume Template Gallery — Modern CV Layouts Free | Zubware',
  'resume-version-manager': 'Resume Version Manager — Organize Multiple CVs | Zubware',
  'resume-import': 'Resume Importer — Import LinkedIn & PDF to CV | Zubware',
  'resume-export': 'Resume Exporter — Download Print-Ready PDF & DOCX | Zubware',
  'resume-completeness': 'Resume Completeness Score — CV Quality Checker | Zubware',
  'resume-section-manager': 'Resume Section Manager — Custom CV Headings | Zubware',
  'professional-skill-library': 'Resume Skills Library — Top In-Demand Industry Skills | Zubware',
  'summary-generator': 'Resume Summary Generator — AI Profile Statements | Zubware',
  'resume-color-themes': 'Resume Color Themes — Custom Styling & Palettes | Zubware',
  'experience-calculator': 'Work Experience Calculator — Total Career Years | Zubware',
  'notice-period-calculator': 'Notice Period Calculator — Last Working Day Date | Zubware',
  'salary-hike-calculator': 'Salary Hike Calculator — Percentage Hike & New CTC | Zubware',
  'ctc-calculator': 'CTC to In-Hand Calculator — Net Take Home Salary | Zubware',
  'working-days-calculator': 'Working Days Calculator — Business Days Between Dates | Zubware',

  // --- Creator & Social Media Tools ---
  'youtube-title-generator': 'YouTube Title Generator — Viral Video Title Maker | Zubware',
  'youtube-description-generator': 'YouTube Description Generator — SEO Descriptions | Zubware',
  'youtube-tags-generator': 'YouTube Tags Generator — High Rank SEO Video Tags | Zubware',
  'youtube-hashtag-generator': 'YouTube Hashtag Generator — Trending Video Hashtags | Zubware',
  'youtube-thumbnail-preview': 'YouTube Thumbnail Preview — Test Title & CTR Online | Zubware',
  'youtube-thumbnail-simulator': 'YouTube Thumbnail Simulator — Mobile Feed CTR Preview | Zubware',
  'youtube-banner-safe-area': 'YouTube Banner Safe Area — Preview Channel Art Online | Zubware',
  'youtube-channel-name-generator': 'YouTube Channel Name Generator — Catchy Ideas | Zubware',
  'youtube-video-idea-generator': 'YouTube Video Idea Generator — Viral Content Topics | Zubware',
  'youtube-playlist-name-generator': 'YouTube Playlist Name Generator — SEO Playlist Titles | Zubware',
  'youtube-timestamp-generator': 'YouTube Timestamp Generator — Video Chapter Maker | Zubware',
  'youtube-description-formatter': 'YouTube Description Formatter — Clean Layouts | Zubware',
  'thumbnail-text-generator': 'Thumbnail Text Generator — High-CTR Clickable Copy | Zubware',
  'viral-hook-generator': 'Viral Hook Generator — Catchy Video Intros & Openers | Zubware',
  'cta-generator': 'Call to Action Generator — High-Converting CTAs | Zubware',
  'social-character-counter': 'Social Character Counter — Twitter, IG & LinkedIn | Zubware',
  'emoji-generator': 'Emoji Selector & Generator — Copy Trending Emojis | Zubware',
  'instagram-caption-generator': 'Instagram Caption Generator — Viral Aesthetic Copy | Zubware',
  'instagram-hashtag-generator': 'Instagram Hashtag Generator — Best Reach Tags | Zubware',
  'instagram-bio-generator': 'Instagram Bio Generator — Aesthetic Profile Bios | Zubware',
  'instagram-username-generator': 'Instagram Username Generator — Unique Handle Ideas | Zubware',
  'tiktok-caption-generator': 'TikTok Caption Generator — Viral Video Captions | Zubware',
  'tiktok-hashtag-generator': 'TikTok Hashtag Generator — Trending FYP Hashtags | Zubware',
  'facebook-caption-generator': 'Facebook Caption Generator — Engaging Post Captions | Zubware',
  'facebook-hashtag-generator': 'Facebook Hashtag Generator — Trending Page Tags | Zubware',
  'linkedin-headline-generator': 'LinkedIn Headline Generator — Professional Taglines | Zubware',
  'linkedin-summary-generator': 'LinkedIn Summary Generator — About Me Bio Maker | Zubware',
  'twitter-bio-generator': 'Twitter Bio Generator — Catchy X Profile Bios | Zubware',
  'universal-hashtag-generator': 'Universal Hashtag Generator — Multi-Platform Tags | Zubware',
  'fancy-text-generator': 'Fancy Text Generator — Cool Aesthetic Unicode Fonts | Zubware',
  'unicode-font-generator': 'Unicode Font Generator — Copy Cursive & Bold Text | Zubware',
  'text-decorator': 'Text Decorator — Stylish Symbols & Borders Online | Zubware',
  'emoji-combiner': 'Emoji Combiner — Kitchen Mix & Blend Emoji Stickers | Zubware',
  'social-media-post-formatter': 'Social Post Formatter — Clean Spacing & Line Breaks | Zubware',
  'social-bio-link-builder': 'Bio Link Page Builder — Free Linktree Alternative | Zubware',
  'islamic-shorts-maker': 'Islamic Shorts Maker — 9:16 Video Quotes & Verses | Zubware',
  'script-to-video-maker': 'Script to Video Maker — Scrolling Text Reels Online | Zubware',

  // --- Developer & Data Tools ---
  'uuid-generator': 'UUID Generator — Bulk v1 & v4 UUID/GUID Online | Zubware',
  'hash-generator': 'Hash Generator — MD5, SHA-1, SHA-256 & SHA-512 | Zubware',
  'jwt-decoder': 'JWT Decoder — Decode & Inspect JSON Web Tokens | Zubware',
  'unix-timestamp-converter': 'Unix Timestamp Converter — Epoch to Human Date | Zubware',
  'regex-tester': 'Regex Tester & Explainer — Test Regular Expressions | Zubware',
  'json-formatter': 'JSON Formatter — Beautify & Validate JSON Online | Zubware',
  'json-validator': 'JSON Validator — Check JSON Syntax & Detect Errors | Zubware',
  'json-to-csv': 'JSON to CSV Converter — Export JSON to Spreadsheet | Zubware',
  'csv-to-json': 'CSV to JSON Converter — Convert CSV Data to JSON | Zubware',
  'csv-viewer': 'CSV Viewer & Editor — View Tabular Data Online Free | Zubware',
  'website-downloader': 'Website Asset Downloader — Save Web Images & CSS | Zubware',
  'html-formatter': 'HTML Formatter & Beautifier — Format HTML Code Free | Zubware',
  'css-formatter': 'CSS Formatter & Beautifier — Clean & Indent Styles | Zubware',
  'javascript-formatter': 'JavaScript Formatter — Beautify JS & TS Scripts | Zubware',
  'xml-formatter': 'XML Formatter & Beautifier — Clean Indented XML | Zubware',
  'xml-validator': 'XML Validator — Detect Malformed XML Syntax Online | Zubware',
  'url-parser': 'URL Parser & Analyzer — Query Params & Hostname | Zubware',
  'url-encoder-decoder': 'URL Encoder & Decoder — Encode URI Components Online | Zubware',
  'base64-encoder-decoder': 'Base64 Encoder & Decoder — Text & Binary Base64 | Zubware',
  'html-escape-unescape': 'HTML Escape & Unescape — Convert HTML Entities | Zubware',
  'http-header-viewer': 'HTTP Header Viewer — Inspect Response & CORS Headers | Zubware',
  'api-request-builder': 'API Request Builder — Test REST API Endpoints Free | Zubware',

  // --- CSS & Design Tools ---
  'color-converter': 'Color Converter — HEX, RGB, HSL & CMYK with Contrast | Zubware',
  'qr-code-decoder': 'QR Code Decoder — Scan & Read QR Codes from Images | Zubware',
  'css-gradient-generator': 'CSS Gradient Generator — Linear & Radial Gradients | Zubware',
  'box-shadow-generator': 'CSS Box Shadow Generator — Multi-Layer Shadow Code | Zubware',
  'border-radius-generator': 'CSS Border Radius Generator — Fancy Smooth Corners | Zubware',
  'glassmorphism-generator': 'CSS Glassmorphism Generator — Frosted Glass UI | Zubware',
  'neumorphism-generator': 'CSS Neumorphism Generator — Soft UI Shadows Code | Zubware',
  'css-clip-path-generator': 'CSS Clip Path Generator — Custom Polygon Shapes | Zubware',
  'svg-shape-generator': 'SVG Shape Generator — Waves, Blobs & Organic Vectors | Zubware',
  'color-palette-generator': 'Color Palette Generator — Harmonious Hex Schemes | Zubware',
  'contrast-checker': 'WCAG Contrast Checker — Accessible Color Ratios | Zubware',
  'random-color-generator': 'Random Color Generator — Generate Hex & RGB Hues | Zubware',
  'qr-business-card-generator': 'vCard QR Code Generator — Digital Business Cards | Zubware',

  // --- Calculators & Math Tools ---
  'unit-converter': 'Unit Converter — Metric, Imperial, Length & Weight | Zubware',
  'percentage-calculator': 'Percentage Calculator — Find Increase & Difference | Zubware',
  'age-calculator': 'Age Calculator — Calculate Exact Age from DOB | Zubware',
  'emi-calculator': 'EMI Calculator — Loan EMI, Interest & Schedule | Zubware',
  'discount-calculator': 'Discount Calculator — Calculate Sale Price & Savings | Zubware',
  'currency-calculator': 'Currency Exchange Calculator — Live FX Rates Free | Zubware',
  'tip-calculator': 'Tip Calculator — Split Bill & Calculate Gratuity | Zubware',
  'random-number-generator': 'Random Number Generator — True Random Range Picker | Zubware',
  'random-password-generator': 'Password Generator — Create Strong Secure Passwords | Zubware',
  'number-to-words': 'Number to Words Converter — English & Currency Words | Zubware',
  'words-to-number': 'Words to Number Converter — Parse Written Numbers | Zubware',
  'roman-numeral-converter': 'Roman Numeral Converter — Numbers to Roman Numerals | Zubware',
  'loan-calculator': 'Loan Calculator — Amortization Schedule & Interest | Zubware',
  'roi-calculator': 'ROI Calculator — Return on Investment & Profit | Zubware',
  'compound-interest-calculator': 'Compound Interest Calculator — Investment Growth | Zubware',

  // --- AI Prompt Builders ---
  'chatgpt-prompt-builder': 'ChatGPT Prompt Builder — Master AI Prompts & Roles | Zubware',
  'gemini-prompt-builder': 'Gemini Prompt Builder — Structure Prompts for Gemini | Zubware',
  'claude-prompt-builder': 'Claude Prompt Builder — Craft Effective Prompts | Zubware',
  'veo-prompt-builder': 'Google Veo Prompt Builder — AI Video Prompts | Zubware',
  'midjourney-prompt-builder': 'Midjourney Prompt Builder — AI Art Image Prompts | Zubware',
  'flux-prompt-builder': 'Flux AI Prompt Builder — High Quality Image Prompts | Zubware',
  'stable-diffusion-prompt-builder': 'Stable Diffusion Prompt Builder — Negative Prompts | Zubware',
  'logo-prompt-builder': 'Logo Prompt Builder — Minimalist & 3D Brand Prompts | Zubware',
  'thumbnail-prompt-builder': 'Thumbnail Prompt Builder — YouTube Visual Ideas | Zubware',
  'product-photo-prompt-builder': 'Product Photo Prompt Builder — Studio Prompts | Zubware',
  'interior-design-prompt-builder': 'Interior Design Prompt Builder — Architecture & Rooms | Zubware',
  'story-prompt-builder': 'Story Prompt Builder — Fiction & Narrative Generator | Zubware',
  'youtube-script-prompt-builder': 'YouTube Script Prompt Builder — Video Scripts | Zubware',
  'resume-prompt-builder': 'Resume Prompt Builder — AI Resume Bullet Points | Zubware',
  'cover-letter-prompt-builder': 'Cover Letter Prompt Builder — Targeted Job Letters | Zubware',
  'email-prompt-builder': 'Email Prompt Builder — Professional Cold Emails | Zubware',
  'social-media-prompt-builder': 'Social Media Prompt Builder — Multi-Platform Posts | Zubware',
  'seo-prompt-builder': 'SEO Prompt Builder — Keywords & Content Briefs | Zubware',
  'coding-prompt-builder': 'Coding Prompt Builder — Code Generation & Debugging | Zubware',
  'universal-prompt-builder': 'Universal Prompt Builder — Frameworks for Any LLM | Zubware',

  // --- Security & Privacy ---
  'password-generator': 'Password Generator — Secure Passwords with Symbols | Zubware',
  'password-strength-checker': 'Password Strength Checker — Test Entropy & Safety | Zubware',
  'qr-code-safety-checker': 'QR Code Safety Checker — Scan Malicious Link URLs | Zubware',
  'qr-code-scanner': 'Online QR Code Scanner — Web Camera QR Reader Free | Zubware',
  'barcode-scanner': 'Online Barcode Scanner — Scan Barcodes via Camera | Zubware',
  'text-encrypt-decrypt': 'Text Encrypt & Decrypt — AES-256 Encrypted Messages | Zubware',
  'sha-checksum-generator': 'SHA Checksum Generator — Verify File Hash Integrity | Zubware',
  'weight-gain-calculator': 'Weight Gain Calorie & Macro Calculator | Zubware',

  // --- PDF Suite ---
  'pdf-size-adjuster': 'PDF Size Adjuster Online – Increase or Reduce PDF Size | Zubware',
  'increase-pdf-size': 'Increase PDF Size Online – Make a PDF Larger | Zubware',
  'decrease-pdf-size': 'Decrease PDF Size Online – Compress PDF | Zubware',
  'pdf-compressor': 'PDF Compressor — Compress PDF Files Online Free | Zubware',
  'pdf-to-jpg': 'PDF to JPG Converter — Convert PDF Pages to Images | Zubware',
  'edit-pdf': 'Online PDF Editor — Add Text, Sign & Edit PDF Free | Zubware',
  'text-to-pdf': 'Text to PDF Converter — Convert TXT to PDF Online | Zubware',
  'signature-maker': 'Online Signature Maker — Draw Digital Signatures | Zubware',
  'signature-resizer': 'Signature Resizer — Resize Signature for Exams | Zubware',
  'photo-signature-joiner': 'Photo & Signature Joiner — Combine for Admit Cards | Zubware',
  'photo-name-date-joiner': 'Name & Date on Photo — Exam Photo Editor Online | Zubware',
  'text-to-handwriting': 'Text to Handwriting Converter — Handwritten Notes | Zubware',
  'omr-sheet-generator': 'OMR Sheet Generator — Printable OMR Answer Sheets | Zubware',
  'pdf-to-word': 'PDF to Word Converter — Convert PDF to DOCX Free | Zubware',
  'word-to-pdf': 'Word to PDF Converter — Convert DOCX to PDF Online | Zubware',
  'pdf-to-text': 'PDF to Text OCR Converter — Extract Text from PDF | Zubware',
  'pdf-to-excel': 'PDF to Excel Converter — Extract Tables to XLSX | Zubware',
  'pdf-page-number': 'Add Page Numbers to PDF — Number PDF Pages Online | Zubware',
  'pdf-compare': 'PDF Compare Tool — Compare Two PDF Files Online | Zubware',
  'pdf-signature': 'Sign PDF Online Free — Place Digital Signatures | Zubware',

  // --- Text & Developer Suite ---
  'barcode-generator': 'Free Barcode Generator — Create Code 128 & EAN-13 | Zubware',
  'case-converter': 'Case Converter — UPPERCASE, lowercase & Title Case | Zubware',
  'word-counter': 'Word Counter — Count Words, Characters & Readability | Zubware',
  'character-counter': 'Character Counter — Letters, Numbers & Symbol Stats | Zubware',
  'reading-time-calculator': 'Reading Time Calculator — Estimate Reading Duration | Zubware',
  'remove-duplicate-lines': 'Remove Duplicate Lines — Deduplicate Text Lists | Zubware',
  'remove-empty-lines': 'Remove Empty Lines — Strip Blank Lines & Whitespace | Zubware',
  'find-and-replace': 'Find and Replace Text — Batch Regex Text Replacer | Zubware',
  'text-compare': 'Text Compare Tool — Online Diff Checker & Difference | Zubware',
  'text-cleaner': 'Text Cleaner — Remove Extra Spaces, Tabs & HTML | Zubware',
  'sort-lines': 'Sort Lines Online — Alphabetical & Numeric Sorter | Zubware',
  'lorem-ipsum-generator': 'Lorem Ipsum Generator — Dummy Placeholder Text | Zubware',
  'markdown-editor': 'Markdown Editor & Live Preview — Export MD & HTML | Zubware',
  'json-minifier': 'JSON Minifier & Compressor — Minify JSON Online | Zubware',
  'json-to-xml': 'JSON to XML Converter — Transform JSON into XML | Zubware',
  'xml-to-json': 'XML to JSON Converter — Convert XML Structure to JSON | Zubware',
  'markdown-to-html': 'Markdown to HTML Converter — Convert MD to HTML | Zubware',
  'sql-formatter': 'SQL Formatter & Beautifier — Format SQL Queries Free | Zubware',
  'jwt-generator': 'JWT Generator & Signer — Create Signed HMAC Tokens | Zubware',
  'cron-expression-generator': 'Cron Expression Generator — Build & Explain Crons | Zubware',

  // --- 39 New Suite Tools ---
  'hex-color-generator': 'Hex Color Generator — Random HTML & CSS Palette | Zubware',
  'rgb-color-generator': 'RGB Color Code Generator & Hex Slider Converter | Zubware',
  'random-name-picker': 'Random Name Picker — Lucky Draw & Raffle Wheel | Zubware',
  'calorie-calculator': 'Daily Calorie Intake Calculator — BMR & TDEE Goal | Zubware',
  'business-name-generator': 'Business Name Generator — Startup Brand Ideas | Zubware',
  'brand-name-generator': 'Brand Name Generator — Company & Domain Ideas | Zubware',
  'coin-flip': 'Online Coin Flip Simulator — 3D Heads or Tails | Zubware',
  'json-viewer': 'JSON Viewer & Tree Formatter — Object Inspector | Zubware',
  'name-picker-wheel': 'Name Picker Wheel — Random Raffle Winner Spin | Zubware',
  'loan-eligibility-calculator': 'Loan Eligibility Calculator — Borrowing Capacity | Zubware',
  'countdown-calculator': 'Countdown Calculator — Exact Days, Hours & Timer | Zubware',
  'stopwatch': 'Online Stopwatch — Millisecond Precision Lap Timer | Zubware',
  'online-stopwatch': 'Online Stopwatch — Millisecond Precision Lap Timer | Zubware',
  'countdown-timer': 'Countdown Timer — Online Timer with Custom Alarm Chime | Zubware',
  'online-clock': 'Online Clock & World Clock — Accurate Current Time | Zubware',
  'time-zone-converter': 'Time Zone Converter — World Meeting & Time Zone Planner | Zubware',
  'timezone-converter': 'World Time Zone Converter — Meeting Time Planner | Zubware',
  'dice-roller': '3D Dice Roller Simulator — Multi-Dice D6 & D20 | Zubware',
  'down-payment-calculator': 'Down Payment Calculator — Mortgage Savings Goal | Zubware',
  'cement-calculator': 'Cement Concrete Calculator — Bags, Sand & Gravel | Zubware',
  'wavelength-calculator': 'Wavelength Calculator — Light & Wave Frequency | Zubware',
  'user-agent-parser': 'User Agent Parser — Browser, Device & OS Lookup | Zubware',
  'mode-calculator': 'Mode Calculator — Statistical Dataset Frequency | Zubware',
  'inductance-calculator': 'Inductance Calculator — Coil Turns & Solenoid | Zubware',
  'random-letter-generator': 'Random Letter Generator — Alphabet Picker Online | Zubware',
  'water-intake-calculator': 'Daily Water Intake Calculator — Hydration Needs | Zubware',
  'json-to-yaml': 'JSON to YAML Converter — Format Configs Online | Zubware',
  'url-extractor': 'URL Extractor — Scrape & Filter Web Links Online | Zubware',
  'bond-yield-calculator': 'Bond Yield Calculator — Current Yield & YTM | Zubware',
  'cat-age-calculator': 'Cat Age Calculator — Convert Feline to Human Age | Zubware',
  'exam-score-calculator': 'Exam Score Calculator — Test Grade & Percentage | Zubware',
  'cgpa-calculator': 'CGPA to Percentage Calculator — University Grade | Zubware',
  'mileage-calculator': 'Car Gas Mileage Calculator — MPG & Fuel Economy | Zubware',
  'paint-cost-calculator': 'Paint Cost Calculator — Room Wall Area Coverage | Zubware',
  'density-calculator': 'Density Calculator — Mass, Volume & Material | Zubware',
  'screen-size-calculator': 'Screen Size Calculator — Monitor Dimensions & PPI | Zubware',
  'torque-calculator': 'Torque Calculator — Force, Distance & Motor RPM | Zubware',
  'linear-regression-calculator': 'Linear Regression Calculator — Best Fit y = mx+b | Zubware',
  'sha256-hash-generator': 'SHA-256 Hash Generator — Real-Time Checksum | Zubware',
  'us-income-tax-calculator': 'US Income Tax Calculator — 2024 Federal Brackets | Zubware',
  'personal-loan-calculator': 'Personal Loan Calculator — Monthly EMI & APR | Zubware',
  'sale-price-calculator': 'Sale Price Calculator — Stacked Coupon Discount | Zubware',
  'md5-hash-generator': 'MD5 Hash Generator — 128-Bit Checksum Digest | Zubware',
  'wide-text-generator': 'Wide Text Generator — Fullwidth Vaporwave Font | Zubware',

  // --- New Global High-Intent Utility Suite ---
  'typing-speed-test': 'Typing Speed Test — Check WPM & Accuracy Free | Zubware',
  'text-reverser': 'Text Reverser — Reverse Words & Backwards Text | Zubware',
  'remove-line-breaks': 'Remove Line Breaks — Clean Text & Paragraphs | Zubware',
  'remove-extra-spaces': 'Remove Extra Spaces — Clean Whitespace & Indents | Zubware',
  'text-repeater': 'Text Repeater — Repeat Words & Strings 10,000x | Zubware',
  'text-splitter': 'Text Splitter — Split Text by Delimiter or Chunks | Zubware',
  'text-joiner': 'Text Joiner — Combine Lines with Custom Delimiters | Zubware',
  'email-extractor': 'Email Extractor — Scrape & Filter Emails Online | Zubware',
  'keyword-extractor': 'Keyword Extractor — Extract SEO Keywords & Density | Zubware',
  'html-entity-encoder-decoder': 'HTML Entity Encoder & Decoder — Convert & Special Chars | Zubware',
  'text-to-binary': 'Text to Binary Converter — ASCII to 0s & 1s Code | Zubware',
  'binary-to-text': 'Binary to Text Converter — Decode 0s & 1s to Text | Zubware',
  'text-to-hex': 'Text to Hex Converter — ASCII to Hexadecimal Strings | Zubware',
  'hex-to-text': 'Hex to Text Converter — Decode Hex to Plain Text Online | Zubware',
  'css-minifier': 'CSS Minifier — Minify CSS Online for Faster Speeds | Zubware',
  'javascript-minifier': 'JavaScript Minifier — Minify JS Code Online Free | Zubware',
  'html-minifier': 'HTML Minifier — Compress HTML Online for SEO Speed | Zubware',
  'sql-minifier': 'SQL Minifier — Compress SQL Queries to Single Line | Zubware',
  'meta-tag-generator': 'Meta Tag Generator — Generate SEO & Open Graph Tags | Zubware',
  'robots-txt-generator': 'Robots.txt Generator — Create SEO-Friendly Robots.txt | Zubware',
  'xml-sitemap-generator': 'XML Sitemap Generator — Create Google Sitemaps Free | Zubware',
  'schema-markup-generator': 'Schema Markup Generator — JSON-LD Structured Data | Zubware',
  'utm-builder': 'UTM Builder — Google Analytics Campaign URL Generator | Zubware',
  'scientific-calculator': 'Scientific Calculator — Advanced Math & Trigonometry | Zubware',
  'handwriting-to-text': 'Handwriting to Text OCR — Extract Handwritten Notes | Zubware',
  'image-to-text': 'Image to Text OCR Converter — Extract Text from Photos | Zubware',
  'calendar-notes': 'Calendar Notes — Private Monthly Calendar & Planner | Zubware',
  'clipboard-history': 'Clipboard History Manager — Save & Search Snippets | Zubware',
  'daily-planner': 'Daily Routine Planner — Morning, Afternoon & Evening | Zubware',
  'expense-tracker': 'Personal Expense Tracker — Income & Expenses Ledger | Zubware',
  'file-checksum-verifier': 'File Checksum Verifier — Verify SHA-256 & MD5 | Zubware',
  'habit-tracker': 'Daily Habit Tracker — Build Positive Habits & Streaks | Zubware',
  'monthly-budget-planner': 'Monthly Budget Planner — Category Spending Limits | Zubware',
  'passphrase-generator': 'Passphrase Generator — Memorable Diceware Passwords | Zubware',
  'pomodoro-timer': 'Pomodoro Focus Timer — 25-Min Intervals & Chimes | Zubware',
  'secure-notes': 'Secure Offline Notes — Private Encrypted Notepad | Zubware',
  'todo-list': 'Todo List & Task Manager — Priority Checklist Online | Zubware',
  'weekly-planner': '7-Day Weekly Planner — Schedule Monday to Sunday | Zubware',
  'random-text-generator': 'Random Text & String Generator — Custom Character Sets | Zubware',
  'subtitle-generator': 'Video Subtitle & SRT Generator — Sync Captions Online | Zubware',
  'video-aspect-ratio': 'Video Aspect Ratio Converter — 9:16 Reels & Shorts | Zubware',
  'video-compressor': 'Video Compressor — Reduce Video File Size In Browser | Zubware',
  'video-to-audio': 'Video to Audio Extractor — Convert MP4 & WebM to WAV | Zubware',
  'video-to-gif': 'Video to GIF Converter — Create Animated GIFs Online | Zubware',
  'video-trimmer': 'Video Trimmer & Cutter — Cut Video Segments Free | Zubware'
};

/**
 * Returns a search-engine-optimized, click-optimized title for any tool.
 * Guarantees optimal 45–65 character length, rich keyword density, and brand consistency.
 */
export function getToolSeoTitle(tool: ToolMeta): string {
  if (tool.seoTitle) {
    return tool.seoTitle;
  }

  const mapped = TOOL_SEO_TITLES[tool.id];
  if (mapped) {
    return mapped;
  }

  // Graceful, robust fallback for future dynamic tools:
  let cleanBase = tool.title.replace(/\s*\|\s*(?:SplitDrop|Zubware)/gi, '').trim();
  if (cleanBase.includes('—')) {
    return `${cleanBase} | Zubware`;
  }
  return `${cleanBase} — Free Online Tool | Zubware`;
}
