import React from 'react';
import { AlertCircle, Shield } from 'lucide-react';

interface DisclaimerPageProps {
  onNavigate: (path: string) => void;
}

export const DisclaimerPage: React.FC<DisclaimerPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 my-8">
      <div className="text-center max-w-2xl mx-auto">
        <span className="p-3 rounded-2xl bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 inline-block mb-3">
          <AlertCircle className="w-8 h-8" />
        </span>
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white">
          Website Disclaimer
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-2">
          General Information & Accuracy Disclaimer • www.zubware.com
        </p>
      </div>

      <div className="glass-panel p-6 sm:p-10 rounded-3xl space-y-6 text-slate-700 dark:text-slate-300 text-xs sm:text-sm leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-extrabold text-slate-900 dark:text-white">General Information Only</h2>
          <p>
            The information, calculators, converters, and software utilities provided across Zubware (www.zubware.com) are for general utility, developer assistance, educational, and productivity purposes. Local tools process data directly inside the user's web browser memory.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-extrabold text-slate-900 dark:text-white">No Professional Financial, Tax, or Legal Advice</h2>
          <p>
            Calculators (including the US Federal & State Income Tax Calculator, India Budget 2025-2026 Tax Regime Comparator, Down Payment Savings Roadmap, Mortgage Estimator, and Personal Loan Calculator) are mathematical simulation models intended solely for personal budgeting and estimation purposes.
          </p>
          <p>
            Tax rules, statutory standard deductions, state brackets, and rebate provisions (such as Section 87A and IRS inflation adjustments) frequently evolve. Results generated by Zubware do not constitute certified tax filings, legal counsel, or financial planning advice. We strongly advise verifying all financial and tax obligations with a certified Chartered Accountant (CA), Certified Public Accountant (CPA), or licensed financial advisor before filing returns or making real estate commitments.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-extrabold text-slate-900 dark:text-white">External Links & Third-Party Resources</h2>
          <p>
            Zubware may contain links leading to external websites, documentation, or third-party resources for user convenience. Zubware does not control, operate, or endorse third-party content and assumes no responsibility for their policies, availability, or accuracy.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-extrabold text-slate-900 dark:text-white">Limitation of Liability</h2>
          <p>
            All utilities on Zubware are provided on an "as is" and "as available" basis without warranties of any kind. Under no circumstances shall Zubware be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our tools, calculations, or resources.
          </p>
        </section>
      </div>
    </div>
  );
};
