import { IslamicTemplatePreset, Layer, BackgroundConfig } from './types';

export const TEMPLATE_PRESETS: IslamicTemplatePreset[] = [
  {
    id: 'spec-composition-27',
    name: 'Hindi Islamic Short (Special Composition)',
    category: 'Hindi / Urdu Special',
    thumbnailColor: '#0a231c',
    thumbnailColor2: '#184d3b',
    accentColor: '#fbbf24',
    description: 'Bismillah frame, 99 Martaba, Durood instruction, dual Arabic Dua & Hindi translation with lanterns',
    background: {
      type: 'gradient-linear',
      color1: '#071d18',
      color2: '#0e3a2d',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      // Top Frame Gold
      {
        id: 'frame-1',
        name: 'Gold Border Frame',
        type: 'decoration',
        decoType: 'frame-gold',
        x: 540,
        y: 960,
        width: 1000,
        height: 1840,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        hidden: false,
        color: '#f59e0b'
      },
      // Hanging Lanterns
      {
        id: 'lanterns-1',
        name: 'Top Lanterns',
        type: 'decoration',
        decoType: 'lantern',
        x: 540,
        y: 120,
        width: 800,
        height: 180,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        color: '#fef08a'
      },
      // Bismillah Badge
      {
        id: 'bismillah-txt',
        name: 'Bismillah Header',
        type: 'text',
        text: 'بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ',
        fontFamily: 'Amiri, serif',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#fde047',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 190,
        width: 900,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      // Main Heading
      {
        id: 'heading-txt',
        name: 'Main Heading',
        type: 'text',
        text: '99 मर्तबा पढ़ें',
        fontFamily: 'sans-serif',
        fontSize: 64,
        fontWeight: '900',
        color: '#fbbf24',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 10,
        shadowOffsetY: 4,
        x: 540,
        y: 280,
        width: 900,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      // Instruction 1
      {
        id: 'instruction-1',
        name: 'Instruction 1',
        type: 'text',
        text: 'सबसे पहले 3 मर्तबा दुरूद शरीफ पढ़ें',
        fontFamily: 'sans-serif',
        fontSize: 32,
        fontWeight: 'bold',
        color: '#f8fafc',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        backgroundColor: 'rgba(245, 158, 11, 0.2)',
        backgroundPadding: 12,
        backgroundRadius: 16,
        x: 540,
        y: 375,
        width: 820,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      // Gold Divider 1
      {
        id: 'div-1',
        name: 'Gold Divider',
        type: 'decoration',
        decoType: 'divider-gold',
        x: 540,
        y: 450,
        width: 600,
        height: 30,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        hidden: false,
        color: '#fbbf24'
      },
      // Arabic Dua 1
      {
        id: 'arabic-dua-1',
        name: 'Arabic Dua 1',
        type: 'text',
        text: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ',
        fontFamily: 'Amiri, serif',
        fontSize: 54,
        fontWeight: 'bold',
        color: '#fef08a',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        backgroundPadding: 20,
        backgroundRadius: 24,
        strokeColor: '#f59e0b',
        strokeWidth: 1,
        x: 540,
        y: 580,
        width: 920,
        height: 180,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      // Hindi Transliteration 1
      {
        id: 'translit-1',
        name: 'Hindi Transliteration 1',
        type: 'text',
        text: 'ला हवला वला कुव्वता इल्ला बिल्लाहिल अलिय्यिल अज़ीम',
        fontFamily: 'sans-serif',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 730,
        width: 880,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      // Second Section Header
      {
        id: 'instruction-2',
        name: 'Instruction 2',
        type: 'text',
        text: 'फिर 100 बार यह तस्बीह पढ़ें:',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#38bdf8',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        x: 540,
        y: 830,
        width: 800,
        height: 45,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      // Arabic Dua 2
      {
        id: 'arabic-dua-2',
        name: 'Arabic Dua 2',
        type: 'text',
        text: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ',
        fontFamily: 'Amiri, serif',
        fontSize: 52,
        fontWeight: 'bold',
        color: '#bae6fd',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        backgroundPadding: 20,
        backgroundRadius: 24,
        x: 540,
        y: 970,
        width: 920,
        height: 170,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      // Hindi Transliteration 2
      {
        id: 'translit-2',
        name: 'Hindi Transliteration 2',
        type: 'text',
        text: 'सुब्हानल्लाही व बिहम्दिही सुब्हानल्लाहिल अज़ीम',
        fontFamily: 'sans-serif',
        fontSize: 32,
        fontWeight: 'bold',
        color: '#e0f2fe',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 1110,
        width: 880,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      // Explanation & Benefits
      {
        id: 'explanation-txt',
        name: 'Explanation Text',
        type: 'text',
        text: 'फज़ीलत: इस वज़ीफ़े को पढ़ने से अल्लाह तआला तमाम परेशानियाँ दूर फरमाता है और रिज़्क़ में बेहिसाब बरकत अता फरमाता है।',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'normal',
        color: '#d1fae5',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 0,
        x: 540,
        y: 1250,
        width: 880,
        height: 120,
        rotation: 0,
        opacity: 0.95,
        locked: false,
        hidden: false
      },
      // Reference Text
      {
        id: 'ref-txt',
        name: 'Reference Text',
        type: 'text',
        text: '— [ सहीह अल-बुख़ारी: 6405 ] —',
        fontFamily: 'sans-serif',
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#fbbf24',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1370,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      // Bottom Mosque Silhouette / Quran Ornament
      {
        id: 'quran-ornament',
        name: 'Quran Decoration',
        type: 'decoration',
        decoType: 'quran',
        x: 540,
        y: 1510,
        width: 140,
        height: 100,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        hidden: false,
        color: '#fbbf24'
      },
      // CTA Button
      {
        id: 'cta-btn',
        name: 'CTA Share Button',
        type: 'text',
        text: 'शेयर जरूर करें 🤲 | सवाब-ए-जारिया',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#071d18',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#fbbf24',
        backgroundPadding: 16,
        backgroundRadius: 30,
        x: 540,
        y: 1660,
        width: 720,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  },
  {
    id: 'dua-daily-emerald',
    name: 'Daily Dua Emerald Gold',
    category: 'Daily Dua',
    thumbnailColor: '#064e3b',
    thumbnailColor2: '#022c22',
    accentColor: '#f59e0b',
    description: 'Emerald green gradient canvas with gold arch mihrab and hanging lanterns',
    background: {
      type: 'gradient-linear',
      color1: '#064e3b',
      color2: '#022c22',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      {
        id: 'arch-1',
        name: 'Mihrab Arch',
        type: 'decoration',
        decoType: 'frame-arch',
        x: 540,
        y: 960,
        width: 980,
        height: 1800,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        hidden: false,
        color: '#f59e0b'
      },
      {
        id: 'lanterns-2',
        name: 'Lanterns',
        type: 'decoration',
        decoType: 'lantern',
        x: 540,
        y: 130,
        width: 800,
        height: 180,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        color: '#fde047'
      },
      {
        id: 'badge-2',
        name: 'Badge Header',
        type: 'text',
        text: 'Daily Dua • دعاء اليوم',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        color: '#f59e0b',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 2,
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        backgroundPadding: 12,
        backgroundRadius: 24,
        strokeColor: '#f59e0b',
        strokeWidth: 1,
        x: 540,
        y: 230,
        width: 500,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'title-2',
        name: 'Title Heading',
        type: 'text',
        text: 'Forgiveness of All Sins',
        fontFamily: 'Cinzel, serif',
        fontSize: 52,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        x: 540,
        y: 330,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'arabic-2',
        name: 'Arabic Text',
        type: 'text',
        text: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ',
        fontFamily: 'Amiri, serif',
        fontSize: 60,
        fontWeight: 'bold',
        color: '#fef08a',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        backgroundPadding: 24,
        backgroundRadius: 28,
        x: 540,
        y: 620,
        width: 920,
        height: 240,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      {
        id: 'transl-2',
        name: 'Translation',
        type: 'text',
        text: 'Glory be to Allah and praise be to Him, Glory be to Allah the Supreme.',
        fontFamily: 'sans-serif',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#ecfdf5',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 890,
        width: 880,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'desc-2',
        name: 'Explanation',
        type: 'text',
        text: 'Whoever says this 100 times in a day, his sins will be forgiven even if they were like the foam of the sea.',
        fontFamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#a7f3d0',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 0,
        x: 540,
        y: 1100,
        width: 860,
        height: 120,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'ref-2',
        name: 'Reference',
        type: 'text',
        text: '— [ Sahih al-Bukhari 6405 ] —',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#f59e0b',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1270,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'mosque-2',
        name: 'Mosque Base',
        type: 'decoration',
        decoType: 'mosque',
        x: 540,
        y: 1520,
        width: 800,
        height: 220,
        rotation: 0,
        opacity: 0.25,
        locked: false,
        hidden: false,
        color: '#f59e0b'
      },
      {
        id: 'cta-2',
        name: 'CTA Button',
        type: 'text',
        text: 'Share Zaroor Karein 🤲 | Sawab-e-Jariya',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#022c22',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#f59e0b',
        backgroundPadding: 16,
        backgroundRadius: 32,
        x: 540,
        y: 1720,
        width: 720,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  },
  {
    id: 'luxury-royal-gold',
    name: 'Premium Royal Gold (Ayat al-Kursi)',
    category: 'Luxury Gold',
    thumbnailColor: '#1c1917',
    thumbnailColor2: '#000000',
    accentColor: '#fbbf24',
    description: 'Black velvet background with rich double gold geometric borders and glowing typography',
    background: {
      type: 'gradient-linear',
      color1: '#1c1917',
      color2: '#000000',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      {
        id: 'frame-3',
        name: 'Double Gold Frame',
        type: 'decoration',
        decoType: 'frame-gold',
        x: 540,
        y: 960,
        width: 1000,
        height: 1840,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        color: '#fbbf24'
      },
      {
        id: 'crescent-3',
        name: 'Crescent Moon',
        type: 'decoration',
        decoType: 'crescent',
        x: 540,
        y: 180,
        width: 90,
        height: 90,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        color: '#fbbf24'
      },
      {
        id: 'title-3',
        name: 'Ayat al-Kursi Title',
        type: 'text',
        text: 'آيَةُ الْكُرْسِيِّ • Ayat al-Kursi',
        fontFamily: 'Amiri, serif',
        fontSize: 48,
        fontWeight: 'bold',
        color: '#fbbf24',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 2,
        x: 540,
        y: 310,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'div-3',
        name: 'Gold Divider',
        type: 'decoration',
        decoType: 'divider-gold',
        x: 540,
        y: 390,
        width: 700,
        height: 30,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false,
        color: '#fbbf24'
      },
      {
        id: 'arabic-3',
        name: 'Arabic Verses',
        type: 'text',
        text: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
        fontFamily: 'Amiri, serif',
        fontSize: 54,
        fontWeight: 'bold',
        color: '#fef08a',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1,
        backgroundColor: 'rgba(251, 191, 36, 0.08)',
        backgroundPadding: 24,
        backgroundRadius: 28,
        strokeColor: '#fbbf24',
        strokeWidth: 1,
        x: 540,
        y: 680,
        width: 920,
        height: 360,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      {
        id: 'transl-3',
        name: 'English Translation',
        type: 'text',
        text: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep.',
        fontFamily: 'Cinzel, serif',
        fontSize: 32,
        fontWeight: 'normal',
        color: '#fef3c7',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 0,
        x: 540,
        y: 1080,
        width: 880,
        height: 160,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'desc-3',
        name: 'Fazeelat Description',
        type: 'text',
        text: 'Recite before sleeping for divine protection by an angel sent from Allah until morning.',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'normal',
        color: '#d6d3d1',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 1300,
        width: 860,
        height: 80,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        hidden: false
      },
      {
        id: 'ref-3',
        name: 'Reference',
        type: 'text',
        text: '— [ Surah Al-Baqarah 2:255 ] —',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#fbbf24',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1420,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'cta-3',
        name: 'CTA Button',
        type: 'text',
        text: 'Save & Share For Protection 👑',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#000000',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#fbbf24',
        backgroundPadding: 16,
        backgroundRadius: 32,
        x: 540,
        y: 1640,
        width: 720,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  },
  {
    id: 'ramadan-kareem-special',
    name: 'Ramadan Mubarak Special',
    category: 'Ramadan',
    thumbnailColor: '#0f172a',
    thumbnailColor2: '#1e1b4b',
    accentColor: '#38bdf8',
    description: 'Deep night sky with glowing crescent, stars, lanterns and Iftar dua',
    background: {
      type: 'gradient-linear',
      color1: '#0f172a',
      color2: '#1e1b4b',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      {
        id: 'stars-4',
        name: 'Night Stars',
        type: 'decoration',
        decoType: 'stars',
        x: 540,
        y: 200,
        width: 850,
        height: 250,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        hidden: false,
        color: '#38bdf8'
      },
      {
        id: 'lanterns-4',
        name: 'Lanterns',
        type: 'decoration',
        decoType: 'lantern',
        x: 540,
        y: 140,
        width: 800,
        height: 180,
        rotation: 0,
        opacity: 0.95,
        locked: false,
        hidden: false,
        color: '#fde047'
      },
      {
        id: 'title-4',
        name: 'Ramadan Title',
        type: 'text',
        text: 'رَمَضَانُ مُبَارَكٌ • Iftar Ki Dua',
        fontFamily: 'Amiri, serif',
        fontSize: 48,
        fontWeight: 'bold',
        color: '#38bdf8',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 320,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'arabic-4',
        name: 'Iftar Dua Arabic',
        type: 'text',
        text: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الأَجْرُ إِنْ شَاءَ اللَّهُ',
        fontFamily: 'Amiri, serif',
        fontSize: 56,
        fontWeight: 'bold',
        color: '#bae6fd',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1,
        backgroundColor: 'rgba(56, 189, 248, 0.12)',
        backgroundPadding: 24,
        backgroundRadius: 28,
        strokeColor: '#38bdf8',
        strokeWidth: 1,
        x: 540,
        y: 600,
        width: 920,
        height: 220,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      {
        id: 'transl-4',
        name: 'Transliteration & Translation',
        type: 'text',
        text: 'Dhahaba al-dhama’u wabtallat al-‘urooqu wa thabata al-ajru in sha’ Allah.',
        fontFamily: 'sans-serif',
        fontSize: 32,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 840,
        width: 880,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'desc-4',
        name: 'Meaning',
        type: 'text',
        text: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
        fontFamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#e0f2fe',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 1020,
        width: 860,
        height: 100,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'ref-4',
        name: 'Reference',
        type: 'text',
        text: '— [ Sunan Abi Dawud 2357 ] —',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#38bdf8',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1200,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'cta-4',
        name: 'CTA Button',
        type: 'text',
        text: 'Ramadan Special Share Karein 🌙',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#0f172a',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#38bdf8',
        backgroundPadding: 16,
        backgroundRadius: 32,
        x: 540,
        y: 1640,
        width: 720,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  },
  {
    id: 'jummah-mubarak-gold',
    name: 'Jumu\'ah Mubarak Fazeelat',
    category: 'Friday / Jumu\'ah',
    thumbnailColor: '#047857',
    thumbnailColor2: '#065f46',
    accentColor: '#fef08a',
    description: 'Deep green and gold theme for Friday Durood Shareef virtues',
    background: {
      type: 'gradient-linear',
      color1: '#047857',
      color2: '#065f46',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      {
        id: 'arch-5',
        name: 'Arch Frame',
        type: 'decoration',
        decoType: 'frame-arch',
        x: 540,
        y: 960,
        width: 980,
        height: 1800,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        hidden: false,
        color: '#fef08a'
      },
      {
        id: 'title-5',
        name: 'Jummah Title',
        type: 'text',
        text: 'جُمُعَة مُبَارَكَة • Durood Shareef',
        fontFamily: 'Amiri, serif',
        fontSize: 48,
        fontWeight: 'bold',
        color: '#fef08a',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 260,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'arabic-5',
        name: 'Durood Arabic',
        type: 'text',
        text: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
        fontFamily: 'Amiri, serif',
        fontSize: 50,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.35)',
        backgroundPadding: 24,
        backgroundRadius: 28,
        x: 540,
        y: 600,
        width: 920,
        height: 320,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      {
        id: 'transl-5',
        name: 'Hindi / Urdu Translation',
        type: 'text',
        text: 'ऐ अल्लाह! रहमत नाज़िल फरमा हज़रत मुहम्मद ﷺ पर और उनकी आल पर।',
        fontFamily: 'sans-serif',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#ecfdf5',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 930,
        width: 880,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'desc-5',
        name: 'Virtues',
        type: 'text',
        text: 'Send abundant Durood upon Prophet Muhammad ﷺ on the blessed day of Friday for forgiveness and elevation of status.',
        fontFamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#d1fae5',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 1120,
        width: 860,
        height: 100,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'ref-5',
        name: 'Reference',
        type: 'text',
        text: '— [ Jumu\'ah Sunnah Mubarak ] —',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#fef08a',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1290,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'cta-5',
        name: 'CTA Button',
        type: 'text',
        text: 'Jumu\'ah Mubarak Status ✨',
        fontFamily: 'sans-serif',
        fontSize: 30,
        fontWeight: 'bold',
        color: '#065f46',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#fef08a',
        backgroundPadding: 16,
        backgroundRadius: 32,
        x: 540,
        y: 1640,
        width: 720,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  },
  {
    id: 'minimalist-white-clean',
    name: 'Minimal Islamic Cream & Sage',
    category: 'Minimal',
    thumbnailColor: '#fdfbf7',
    thumbnailColor2: '#f3efe6',
    accentColor: '#059669',
    description: 'Clean cream-white backdrop with crisp typography and subtle gold accents',
    background: {
      type: 'solid',
      color1: '#fdfbf7',
      color2: '#f3efe6',
      angle: 180,
      imageSrc: null,
      imageOpacity: 0.3,
      imageBlur: 0
    },
    createLayers: (): Layer[] => [
      {
        id: 'badge-6',
        name: 'Header Badge',
        type: 'text',
        text: 'Islamic Wisdom • حكمة إسلامية',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        color: '#059669',
        align: 'center',
        lineHeight: 1,
        letterSpacing: 2,
        backgroundColor: 'rgba(5, 150, 105, 0.1)',
        backgroundPadding: 12,
        backgroundRadius: 24,
        x: 540,
        y: 220,
        width: 500,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'title-6',
        name: 'Title',
        type: 'text',
        text: 'Purity of Intentions (Niyyat)',
        fontFamily: 'Playfair Display, serif',
        fontSize: 50,
        fontWeight: 'bold',
        color: '#1c1917',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        x: 540,
        y: 320,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'arabic-6',
        name: 'Arabic Hadith',
        type: 'text',
        text: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ',
        fontFamily: 'Amiri, serif',
        fontSize: 64,
        fontWeight: 'bold',
        color: '#047857',
        align: 'center',
        lineHeight: 1.6,
        letterSpacing: 1,
        x: 540,
        y: 580,
        width: 900,
        height: 180,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        isArabic: true
      },
      {
        id: 'transl-6',
        name: 'Translation',
        type: 'text',
        text: 'Actions are judged according to intentions.',
        fontFamily: 'sans-serif',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1f2937',
        align: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        x: 540,
        y: 820,
        width: 880,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      },
      {
        id: 'desc-6',
        name: 'Explanation',
        type: 'text',
        text: 'Purify your heart and align every daily action for the pleasure of Allah alone.',
        fontFamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#4b5563',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 0,
        x: 540,
        y: 1010,
        width: 860,
        height: 100,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'ref-6',
        name: 'Reference',
        type: 'text',
        text: '— [ Sahih al-Bukhari 1 ] —',
        fontFamily: 'sans-serif',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#059669',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: 1,
        x: 540,
        y: 1200,
        width: 800,
        height: 40,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        hidden: false
      },
      {
        id: 'cta-6',
        name: 'CTA Button',
        type: 'text',
        text: 'Simple & Clean Reminder 🌿',
        fontFamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        backgroundColor: '#059669',
        backgroundPadding: 16,
        backgroundRadius: 32,
        x: 540,
        y: 1640,
        width: 700,
        height: 64,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false
      }
    ]
  }
];
