import React from 'react';
import {
  Activity,
  AlignJustify,
  AlignLeft,
  Anchor,
  ArrowDownAZ,
  ArrowLeftRight,
  AtSign,
  Award,
  BadgePercent,
  BarChart2,
  Barcode,
  Binary,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Braces,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  CaseSensitive,
  Cat,
  CheckCheck,
  CheckCircle2,
  CheckSquare,
  Circle,
  Clapperboard,
  ClipboardList,
  Clock,
  Code,
  Code2,
  Coffee,
  Coins,
  Columns,
  Compass,
  Contact,
  Contrast,
  Cpu,
  CreditCard,
  Crop,
  Database,
  Dice5,
  Download,
  Droplets,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  FileArchive,
  FileCheck,
  FileCode,
  FileEdit,
  FilePlus2,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Fingerprint,
  Flame,
  FlipHorizontal2,
  FolderEdit,
  Frame,
  Fuel,
  Gauge,
  GitBranch,
  GitCompare,
  Globe,
  GraduationCap,
  Grid,
  Hash,
  Headphones,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Image,
  Info,
  Instagram,
  Key,
  KeyRound,
  Keyboard,
  Landmark,
  Laptop,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link,
  Link2,
  Linkedin,
  ListFilter,
  ListMusic,
  ListTodo,
  Lock,
  LogOut,
  Mail,
  Maximize,
  Maximize2,
  Megaphone,
  MessageCircle,
  Minimize2,
  Monitor,
  MonitorPlay,
  Moon,
  MousePointerClick,
  Music,
  Music2,
  Network,
  PaintBucket,
  Paintbrush,
  Palette,
  Pen,
  PenTool,
  Percent,
  PieChart,
  PiggyBank,
  Pipette,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  RectangleHorizontal,
  RefreshCw,
  Regex,
  Repeat,
  RotateCw,
  Ruler,
  Scale,
  Scan,
  ScanText,
  Scissors,
  Search,
  Send,
  Server,
  Shapes,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sliders,
  Smile,
  Sparkles,
  Square,
  Stamp,
  Star,
  Subtitles,
  Table,
  Tag,
  Tags,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  Tv,
  Twitter,
  Type,
  Unlock,
  Upload,
  User,
  UserCheck,
  Video,
  Wallet,
  Wand2,
  Watch,
  Youtube,
  Zap,
  LucideIcon
} from 'lucide-react';

export interface ToolIconProps {
  toolId?: string;
  category?: string;
  className?: string;
  iconClassName?: string;
  size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
  showBackground?: boolean;
}

const COLOR_STYLES: Record<string, { bgLight: string; bgDark: string; textColor: string; borderColor: string }> = {
  rose: { bgLight: 'bg-rose-50', bgDark: 'dark:bg-rose-950/40', textColor: 'text-rose-600 dark:text-rose-400', borderColor: 'border-rose-200/70 dark:border-rose-800/40' },
  orange: { bgLight: 'bg-orange-50', bgDark: 'dark:bg-orange-950/40', textColor: 'text-orange-600 dark:text-orange-400', borderColor: 'border-orange-200/70 dark:border-orange-800/40' },
  amber: { bgLight: 'bg-amber-50', bgDark: 'dark:bg-amber-950/40', textColor: 'text-amber-600 dark:text-amber-400', borderColor: 'border-amber-200/70 dark:border-amber-800/40' },
  emerald: { bgLight: 'bg-emerald-50', bgDark: 'dark:bg-emerald-950/40', textColor: 'text-emerald-600 dark:text-emerald-400', borderColor: 'border-emerald-200/70 dark:border-emerald-800/40' },
  teal: { bgLight: 'bg-teal-50', bgDark: 'dark:bg-teal-950/40', textColor: 'text-teal-600 dark:text-teal-400', borderColor: 'border-teal-200/70 dark:border-teal-800/40' },
  cyan: { bgLight: 'bg-cyan-50', bgDark: 'dark:bg-cyan-950/40', textColor: 'text-cyan-600 dark:text-cyan-400', borderColor: 'border-cyan-200/70 dark:border-cyan-800/40' },
  sky: { bgLight: 'bg-sky-50', bgDark: 'dark:bg-sky-950/40', textColor: 'text-sky-600 dark:text-sky-400', borderColor: 'border-sky-200/70 dark:border-sky-800/40' },
  blue: { bgLight: 'bg-blue-50', bgDark: 'dark:bg-blue-950/40', textColor: 'text-blue-600 dark:text-blue-400', borderColor: 'border-blue-200/70 dark:border-blue-800/40' },
  indigo: { bgLight: 'bg-indigo-50', bgDark: 'dark:bg-indigo-950/40', textColor: 'text-indigo-600 dark:text-indigo-400', borderColor: 'border-indigo-200/70 dark:border-indigo-800/40' },
  violet: { bgLight: 'bg-violet-50', bgDark: 'dark:bg-violet-950/40', textColor: 'text-violet-600 dark:text-violet-400', borderColor: 'border-violet-200/70 dark:border-violet-800/40' },
  purple: { bgLight: 'bg-purple-50', bgDark: 'dark:bg-purple-950/40', textColor: 'text-purple-600 dark:text-purple-400', borderColor: 'border-purple-200/70 dark:border-purple-800/40' },
  pink: { bgLight: 'bg-pink-50', bgDark: 'dark:bg-pink-950/40', textColor: 'text-pink-600 dark:text-pink-400', borderColor: 'border-pink-200/70 dark:border-pink-800/40' },
  fuchsia: { bgLight: 'bg-fuchsia-50', bgDark: 'dark:bg-fuchsia-950/40', textColor: 'text-fuchsia-600 dark:text-fuchsia-400', borderColor: 'border-fuchsia-200/70 dark:border-fuchsia-800/40' },
  red: { bgLight: 'bg-red-50', bgDark: 'dark:bg-red-950/40', textColor: 'text-red-600 dark:text-red-400', borderColor: 'border-red-200/70 dark:border-red-800/40' },
  slate: { bgLight: 'bg-slate-100', bgDark: 'dark:bg-slate-800', textColor: 'text-slate-700 dark:text-slate-300', borderColor: 'border-slate-200 dark:border-slate-700' }
};

// All 307 tool specific icon mappings
const TOOL_CONFIGS: Record<string, { icon: LucideIcon; color: string }> = {
  'image-splitter-merger': { icon: Columns, color: 'indigo' },
  'learning-licence-mock-test': { icon: Car, color: 'emerald' },
  'background-remover': { icon: Wand2, color: 'violet' },
  'image-compressor': { icon: Minimize2, color: 'amber' },
  'image-converter': { icon: Repeat, color: 'sky' },
  'image-resizer': { icon: Maximize2, color: 'blue' },
  'crop-image': { icon: Crop, color: 'emerald' },
  'rotate-image': { icon: RotateCw, color: 'indigo' },
  'flip-image': { icon: FlipHorizontal2, color: 'cyan' },
  'image-watermark': { icon: Stamp, color: 'teal' },
  'blur-image': { icon: EyeOff, color: 'slate' },
  'pixelate-image': { icon: Grid, color: 'orange' },
  'exif-remover': { icon: ShieldAlert, color: 'rose' },
  'image-color-picker': { icon: Pipette, color: 'fuchsia' },
  'image-info-viewer': { icon: Info, color: 'blue' },
  'background-color-changer': { icon: PaintBucket, color: 'purple' },
  'rounded-corners': { icon: Square, color: 'teal' },
  'image-border': { icon: Frame, color: 'amber' },
  'image-frame': { icon: Maximize, color: 'emerald' },
  'image-collage': { icon: LayoutGrid, color: 'violet' },
  'favicon-generator': { icon: Bookmark, color: 'sky' },
  'svg-optimizer': { icon: Zap, color: 'emerald' },
  'gif-maker': { icon: Film, color: 'pink' },
  'batch-image-converter': { icon: Layers, color: 'blue' },
  'compression-comparison': { icon: Scale, color: 'orange' },
  'heic-to-jpg': { icon: RefreshCw, color: 'indigo' },
  'bulk-image-renamer-resizer': { icon: FolderEdit, color: 'cyan' },
  'passport-photo-maker': { icon: Camera, color: 'blue' },
  'signature-maker': { icon: Feather, color: 'teal' },
  'signature-resizer': { icon: Scissors, color: 'sky' },
  'photo-signature-joiner': { icon: FilePlus2, color: 'violet' },
  'photo-name-date-joiner': { icon: CalendarCheck, color: 'amber' },
  'text-to-handwriting': { icon: Pen, color: 'orange' },
  'handwriting-to-text': { icon: ScanText, color: 'indigo' },
  'image-to-text': { icon: FileSearch, color: 'emerald' },
  'pdf-merge': { icon: FilePlus2, color: 'rose' },
  'pdf-split': { icon: Scissors, color: 'orange' },
  'pdf-compressor': { icon: FileArchive, color: 'amber' },
  'decrease-pdf-size': { icon: Minimize2, color: 'amber' },
  'increase-pdf-size': { icon: Maximize2, color: 'blue' },
  'rotate-pdf': { icon: RotateCw, color: 'indigo' },
  'reorder-pdf-pages': { icon: Layers, color: 'violet' },
  'unlock-pdf': { icon: Unlock, color: 'emerald' },
  'protect-pdf': { icon: Lock, color: 'rose' },
  'edit-pdf': { icon: FileText, color: 'sky' },
  'pdf-to-word': { icon: FileText, color: 'blue' },
  'word-to-pdf': { icon: FileCheck, color: 'indigo' },
  'pdf-to-excel': { icon: FileSpreadsheet, color: 'emerald' },
  'pdf-to-images': { icon: Image, color: 'purple' },
  'image-to-pdf': { icon: FilePlus2, color: 'pink' },
  'pdf-signature': { icon: FileCheck, color: 'teal' },
  'pdf-watermark': { icon: Stamp, color: 'cyan' },
  'pdf-page-number': { icon: Hash, color: 'slate' },
  'extract-pdf-pages': { icon: ExternalLink, color: 'orange' },
  'delete-pdf-pages': { icon: Trash2, color: 'rose' },
  'pdf-size-adjuster': { icon: Sliders, color: 'amber' },
  'pdf-to-jpg': { icon: Image, color: 'purple' },
  'text-to-pdf': { icon: FileText, color: 'sky' },
  'pdf-to-text': { icon: ScanText, color: 'teal' },
  'pdf-compare': { icon: GitCompare, color: 'violet' },
  'pdf-metadata': { icon: Info, color: 'blue' },
  'scientific-calculator': { icon: Calculator, color: 'indigo' },
  'matching-parts-video-maker': { icon: Puzzle, color: 'violet' },
  'subtitle-generator': { icon: Subtitles, color: 'sky' },
  'video-aspect-ratio': { icon: Monitor, color: 'pink' },
  'video-cutter': { icon: Scissors, color: 'rose' },
  'video-compressor': { icon: Minimize2, color: 'amber' },
  'video-to-gif': { icon: Film, color: 'purple' },
  'audio-extractor': { icon: Music, color: 'teal' },
  'video-to-audio': { icon: Music, color: 'teal' },
  'video-trimmer': { icon: Scissors, color: 'rose' },
  'lofi-song-maker': { icon: Headphones, color: 'violet' },
  'lofi-maker': { icon: Headphones, color: 'violet' },
  'slowed-and-reverb': { icon: Sliders, color: 'purple' },
  'audio-cutter': { icon: Scissors, color: 'rose' },
  'audio-speed': { icon: FastForward, color: 'amber' },
  'gst-invoice-generator': { icon: Receipt, color: 'indigo' },
  'us-income-tax-calculator': { icon: Landmark, color: 'emerald' },
  'sale-price-calculator': { icon: Tag, color: 'rose' },
  'down-payment-calculator': { icon: Home, color: 'amber' },
  'personal-loan-calculator': { icon: CreditCard, color: 'blue' },
  'compound-interest-calculator': { icon: TrendingUp, color: 'emerald' },
  'loan-mortgage-calculator': { icon: Building2, color: 'cyan' },
  'roi-profit-margin-calculator': { icon: TrendingUp, color: 'violet' },
  'bond-yield-calculator': { icon: Percent, color: 'slate' },
  'mileage-calculator': { icon: Fuel, color: 'orange' },
  'loan-eligibility-calculator': { icon: ShieldCheck, color: 'emerald' },
  'salary-calculator': { icon: Wallet, color: 'teal' },
  'markup-calculator': { icon: BadgePercent, color: 'pink' },
  'margin-calculator': { icon: PieChart, color: 'purple' },
  'omr-sheet-generator': { icon: CheckSquare, color: 'blue' },
  'barcode-generator': { icon: Barcode, color: 'slate' },
  'business-name-generator': { icon: Building2, color: 'amber' },
  'brand-name-generator': { icon: Sparkles, color: 'violet' },
  'expense-tracker': { icon: Wallet, color: 'rose' },
  'monthly-budget-planner': { icon: PiggyBank, color: 'emerald' },
  'resume-builder': { icon: Briefcase, color: 'blue' },
  'experience-calculator': { icon: Clock, color: 'indigo' },
  'resume-completeness': { icon: CheckCircle2, color: 'emerald' },
  'cover-letter-templates': { icon: Mail, color: 'sky' },
  'cover-letter-builder': { icon: Mail, color: 'sky' },
  'professional-skill-library': { icon: Award, color: 'amber' },
  'summary-generator': { icon: Sparkles, color: 'purple' },
  'exam-score-calculator': { icon: GraduationCap, color: 'rose' },
  'cgpa-calculator': { icon: GraduationCap, color: 'indigo' },
  'salary-hike-calculator': { icon: TrendingUp, color: 'emerald' },
  'ctc-calculator': { icon: Calculator, color: 'teal' },
  'working-days-calculator': { icon: CalendarDays, color: 'blue' },
  'resignation-letter': { icon: LogOut, color: 'slate' },
  'job-offer-comparison': { icon: Scale, color: 'violet' },
  'probation-calculator': { icon: Calendar, color: 'amber' },
  'notice-period-calculator': { icon: CalendarClock, color: 'orange' },
  'gratuity-calculator': { icon: Coins, color: 'emerald' },
  'pf-calculator': { icon: Landmark, color: 'blue' },
  'leave-balance-calculator': { icon: Coffee, color: 'teal' },
  'appraisal-score-calculator': { icon: Star, color: 'amber' },
  'overtime-calculator': { icon: Clock, color: 'cyan' },
  'hourly-wage-calculator': { icon: Clock, color: 'indigo' },
  'freelance-rate-calculator': { icon: Laptop, color: 'rose' },
  'career-gap-calculator': { icon: History, color: 'violet' },
  'ats-resume-checker': { icon: FileSearch, color: 'emerald' },
  'resume-score-analyzer': { icon: Gauge, color: 'violet' },
  'cv-builder': { icon: UserCheck, color: 'indigo' },
  'resume-keyword-optimizer': { icon: Key, color: 'amber' },
  'resume-template-gallery': { icon: LayoutTemplate, color: 'pink' },
  'resume-version-manager': { icon: GitBranch, color: 'cyan' },
  'resume-import': { icon: Upload, color: 'blue' },
  'resume-export': { icon: Download, color: 'emerald' },
  'resume-section-manager': { icon: Layers, color: 'teal' },
  'resume-color-themes': { icon: Palette, color: 'rose' },
  'youtube-title-generator': { icon: Youtube, color: 'rose' },
  'youtube-tag-extractor': { icon: Hash, color: 'rose' },
  'youtube-description-generator': { icon: AlignLeft, color: 'rose' },
  'youtube-tags-generator': { icon: Tags, color: 'rose' },
  'youtube-hashtag-generator': { icon: Hash, color: 'rose' },
  'youtube-thumbnail-simulator': { icon: MonitorPlay, color: 'red' },
  'youtube-banner-safe-area': { icon: RectangleHorizontal, color: 'orange' },
  'youtube-thumbnail-preview': { icon: Eye, color: 'rose' },
  'youtube-channel-name-generator': { icon: Tv, color: 'rose' },
  'youtube-video-idea-generator': { icon: Lightbulb, color: 'amber' },
  'youtube-playlist-name-generator': { icon: ListMusic, color: 'rose' },
  'youtube-timestamp-generator': { icon: Timer, color: 'blue' },
  'youtube-description-formatter': { icon: FileText, color: 'rose' },
  'viral-hook-generator': { icon: Flame, color: 'orange' },
  'cta-generator': { icon: MousePointerClick, color: 'emerald' },
  'emoji-generator': { icon: Smile, color: 'amber' },
  'instagram-caption-generator': { icon: Instagram, color: 'pink' },
  'instagram-hashtag-generator': { icon: Hash, color: 'pink' },
  'instagram-bio-generator': { icon: User, color: 'pink' },
  'instagram-username-generator': { icon: AtSign, color: 'fuchsia' },
  'tiktok-hook-generator': { icon: Flame, color: 'purple' },
  'tiktok-caption-generator': { icon: Music2, color: 'purple' },
  'tiktok-hashtag-generator': { icon: Hash, color: 'purple' },
  'facebook-caption-generator': { icon: MessageCircle, color: 'blue' },
  'facebook-hashtag-generator': { icon: Hash, color: 'blue' },
  'linkedin-headline-generator': { icon: Linkedin, color: 'blue' },
  'linkedin-summary-generator': { icon: FileText, color: 'blue' },
  'linkedin-post-generator': { icon: Linkedin, color: 'blue' },
  'tweet-generator': { icon: Twitter, color: 'sky' },
  'twitter-bio-generator': { icon: Twitter, color: 'sky' },
  'social-media-bio-generator': { icon: User, color: 'violet' },
  'universal-hashtag-generator': { icon: Hash, color: 'violet' },
  'fancy-text-generator': { icon: Sparkles, color: 'purple' },
  'unicode-font-generator': { icon: Type, color: 'indigo' },
  'text-decorator': { icon: PenTool, color: 'pink' },
  'emoji-combiner': { icon: Smile, color: 'amber' },
  'social-media-post-formatter': { icon: AlignJustify, color: 'teal' },
  'social-bio-link-builder': { icon: Link, color: 'violet' },
  'islamic-shorts-maker': { icon: Moon, color: 'emerald' },
  'script-to-video-maker': { icon: Clapperboard, color: 'indigo' },
  'video-script-generator': { icon: Film, color: 'indigo' },
  'hook-generator': { icon: Anchor, color: 'orange' },
  'call-to-action-generator': { icon: Megaphone, color: 'emerald' },
  'thumbnail-text-generator': { icon: Type, color: 'amber' },
  'social-character-counter': { icon: Gauge, color: 'teal' },
  'uuid-generator': { icon: Fingerprint, color: 'violet' },
  'json-formatter': { icon: Braces, color: 'emerald' },
  'xml-validator': { icon: FileCode, color: 'amber' },
  'binary-to-text': { icon: Binary, color: 'sky' },
  'sha256-hash-generator': { icon: ShieldCheck, color: 'indigo' },
  'sql-formatter': { icon: Database, color: 'cyan' },
  'base64-encode-decode': { icon: Binary, color: 'purple' },
  'url-encode-decode': { icon: Link2, color: 'blue' },
  'html-entity-encoder': { icon: Code2, color: 'rose' },
  'css-minifier': { icon: FileCode, color: 'teal' },
  'javascript-minifier': { icon: Zap, color: 'amber' },
  'regex-tester': { icon: Regex, color: 'orange' },
  'cron-expression-generator': { icon: Clock, color: 'indigo' },
  'jwt-decoder': { icon: KeyRound, color: 'emerald' },
  'markdown-to-html': { icon: FileCode, color: 'slate' },
  'curl-to-fetch': { icon: Terminal, color: 'sky' },
  'hash-generator': { icon: Hash, color: 'indigo' },
  'unix-timestamp-converter': { icon: Clock, color: 'cyan' },
  'json-validator': { icon: CheckCheck, color: 'emerald' },
  'json-to-csv': { icon: FileSpreadsheet, color: 'teal' },
  'csv-to-json': { icon: Braces, color: 'emerald' },
  'csv-viewer': { icon: Table, color: 'blue' },
  'website-downloader': { icon: Download, color: 'indigo' },
  'html-formatter': { icon: Code2, color: 'orange' },
  'css-formatter': { icon: Palette, color: 'purple' },
  'javascript-formatter': { icon: Zap, color: 'amber' },
  'xml-formatter': { icon: FileCode, color: 'teal' },
  'url-parser': { icon: Link2, color: 'blue' },
  'url-encoder-decoder': { icon: Link2, color: 'sky' },
  'base64-encoder-decoder': { icon: Binary, color: 'purple' },
  'html-escape-unescape': { icon: Code, color: 'rose' },
  'http-header-viewer': { icon: Server, color: 'slate' },
  'api-request-builder': { icon: Send, color: 'indigo' },
  'color-converter': { icon: Pipette, color: 'fuchsia' },
  'qr-code-decoder': { icon: Scan, color: 'violet' },
  'json-minifier': { icon: Minimize2, color: 'amber' },
  'json-to-xml': { icon: Code2, color: 'teal' },
  'xml-to-json': { icon: Braces, color: 'emerald' },
  'jwt-generator': { icon: KeyRound, color: 'indigo' },
  'json-viewer': { icon: Eye, color: 'cyan' },
  'user-agent-parser': { icon: Laptop, color: 'slate' },
  'json-to-yaml': { icon: FileText, color: 'orange' },
  'md5-hash-generator': { icon: ShieldAlert, color: 'rose' },
  'html-entity-encoder-decoder': { icon: Code2, color: 'rose' },
  'text-to-binary': { icon: Binary, color: 'sky' },
  'text-to-hex': { icon: Hash, color: 'indigo' },
  'hex-to-text': { icon: Type, color: 'teal' },
  'html-minifier': { icon: Minimize2, color: 'orange' },
  'sql-minifier': { icon: Minimize2, color: 'cyan' },
  'meta-tag-generator': { icon: Tags, color: 'emerald' },
  'robots-txt-generator': { icon: Bot, color: 'amber' },
  'xml-sitemap-generator': { icon: Network, color: 'indigo' },
  'schema-markup-generator': { icon: Braces, color: 'violet' },
  'utm-builder': { icon: Link2, color: 'blue' },
  'sha-checksum-generator': { icon: ShieldCheck, color: 'indigo' },
  'css-gradient-generator': { icon: Palette, color: 'purple' },
  'box-shadow-generator': { icon: Layers, color: 'blue' },
  'glassmorphism-generator': { icon: Sparkles, color: 'cyan' },
  'neumorphism-generator': { icon: Circle, color: 'slate' },
  'css-clip-path-generator': { icon: Compass, color: 'indigo' },
  'svg-shape-generator': { icon: Shapes, color: 'amber' },
  'color-palette-generator': { icon: Palette, color: 'pink' },
  'contrast-checker': { icon: Contrast, color: 'emerald' },
  'random-color-generator': { icon: Shuffle, color: 'rose' },
  'qr-business-card-generator': { icon: Contact, color: 'violet' },
  'unit-converter': { icon: Ruler, color: 'teal' },
  'percentage-calculator': { icon: Percent, color: 'blue' },
  'age-calculator': { icon: Hourglass, color: 'amber' },
  'emi-calculator': { icon: CreditCard, color: 'indigo' },
  'discount-calculator': { icon: Tag, color: 'rose' },
  'currency-calculator': { icon: Coins, color: 'emerald' },
  'tip-calculator': { icon: Receipt, color: 'teal' },
  'random-number-generator': { icon: Dice5, color: 'violet' },
  'random-password-generator': { icon: KeyRound, color: 'emerald' },
  'number-to-words': { icon: Binary, color: 'sky' },
  'words-to-number': { icon: Type, color: 'indigo' },
  'roman-numeral-converter': { icon: Hash, color: 'amber' },
  'loan-calculator': { icon: Landmark, color: 'cyan' },
  'roi-calculator': { icon: TrendingUp, color: 'violet' },
  'hex-color-generator': { icon: Palette, color: 'purple' },
  'rgb-color-generator': { icon: Sliders, color: 'blue' },
  'random-name-picker': { icon: Shuffle, color: 'rose' },
  'coin-flip': { icon: Coins, color: 'amber' },
  'name-picker-wheel': { icon: HelpCircle, color: 'violet' },
  'countdown-calculator': { icon: CalendarClock, color: 'orange' },
  'online-stopwatch': { icon: Watch, color: 'blue' },
  'countdown-timer': { icon: Timer, color: 'rose' },
  'online-clock': { icon: Clock, color: 'indigo' },
  'time-zone-converter': { icon: Globe, color: 'cyan' },
  'dice-roller': { icon: Dice5, color: 'rose' },
  'cement-calculator': { icon: Building, color: 'slate' },
  'wavelength-calculator': { icon: Radio, color: 'violet' },
  'mode-calculator': { icon: BarChart2, color: 'emerald' },
  'inductance-calculator': { icon: Activity, color: 'amber' },
  'random-letter-generator': { icon: Shuffle, color: 'sky' },
  'cat-age-calculator': { icon: Cat, color: 'pink' },
  'paint-cost-calculator': { icon: Paintbrush, color: 'rose' },
  'density-calculator': { icon: Box, color: 'blue' },
  'screen-size-calculator': { icon: Monitor, color: 'indigo' },
  'torque-calculator': { icon: Gauge, color: 'orange' },
  'linear-regression-calculator': { icon: TrendingUp, color: 'emerald' },
  'border-radius-generator': { icon: Square, color: 'teal' },
  'chatgpt-prompt-builder': { icon: Bot, color: 'emerald' },
  'gemini-prompt-builder': { icon: Sparkles, color: 'blue' },
  'claude-prompt-builder': { icon: Brain, color: 'amber' },
  'veo-prompt-builder': { icon: Video, color: 'purple' },
  'midjourney-prompt-builder': { icon: Image, color: 'indigo' },
  'flux-prompt-builder': { icon: Palette, color: 'rose' },
  'stable-diffusion-prompt-builder': { icon: Wand2, color: 'teal' },
  'logo-prompt-builder': { icon: Shapes, color: 'fuchsia' },
  'thumbnail-prompt-builder': { icon: Image, color: 'pink' },
  'product-photo-prompt-builder': { icon: Camera, color: 'cyan' },
  'interior-design-prompt-builder': { icon: Home, color: 'amber' },
  'story-prompt-builder': { icon: BookOpen, color: 'violet' },
  'youtube-script-prompt-builder': { icon: Youtube, color: 'rose' },
  'resume-prompt-builder': { icon: Briefcase, color: 'blue' },
  'cover-letter-prompt-builder': { icon: Mail, color: 'sky' },
  'email-prompt-builder': { icon: Send, color: 'indigo' },
  'social-media-prompt-builder': { icon: Share2, color: 'pink' },
  'seo-prompt-builder': { icon: Search, color: 'emerald' },
  'coding-prompt-builder': { icon: Code2, color: 'cyan' },
  'universal-prompt-builder': { icon: Cpu, color: 'violet' },
  'qr-code-safety-checker': { icon: ShieldCheck, color: 'emerald' },
  'typing-speed-test': { icon: Keyboard, color: 'indigo' },
  'barcode-scanner': { icon: Barcode, color: 'blue' },
  'calendar-notes': { icon: Calendar, color: 'amber' },
  'clipboard-history': { icon: ClipboardList, color: 'cyan' },
  'daily-planner': { icon: CheckSquare, color: 'violet' },
  'file-checksum-verifier': { icon: FileCheck, color: 'teal' },
  'habit-tracker': { icon: Flame, color: 'rose' },
  'passphrase-generator': { icon: KeyRound, color: 'indigo' },
  'password-strength-checker': { icon: ShieldAlert, color: 'emerald' },
  'pomodoro-timer': { icon: Timer, color: 'rose' },
  'secure-notes': { icon: Lock, color: 'emerald' },
  'text-encrypt-decrypt': { icon: Key, color: 'purple' },
  'todo-list': { icon: ListTodo, color: 'blue' },
  'weekly-planner': { icon: CalendarDays, color: 'violet' },
  'weight-gain-calculator': { icon: Scale, color: 'rose' },
  'calorie-calculator': { icon: Flame, color: 'orange' },
  'water-intake-calculator': { icon: Droplets, color: 'sky' },
  'case-converter': { icon: CaseSensitive, color: 'indigo' },
  'word-counter': { icon: AlignLeft, color: 'blue' },
  'character-counter': { icon: Hash, color: 'teal' },
  'reading-time-calculator': { icon: Clock, color: 'purple' },
  'remove-duplicate-lines': { icon: ListFilter, color: 'orange' },
  'remove-empty-lines': { icon: Minimize2, color: 'amber' },
  'find-and-replace': { icon: Search, color: 'emerald' },
  'text-compare': { icon: GitCompare, color: 'violet' },
  'text-cleaner': { icon: Eraser, color: 'sky' },
  'sort-lines': { icon: ArrowDownAZ, color: 'indigo' },
  'lorem-ipsum-generator': { icon: FileText, color: 'slate' },
  'markdown-editor': { icon: FileEdit, color: 'blue' },
  'url-extractor': { icon: Link2, color: 'teal' },
  'wide-text-generator': { icon: Type, color: 'purple' },
  'text-reverser': { icon: ArrowLeftRight, color: 'rose' },
  'remove-line-breaks': { icon: AlignJustify, color: 'amber' },
  'remove-extra-spaces': { icon: Minimize2, color: 'cyan' },
  'text-repeater': { icon: Repeat, color: 'violet' },
  'text-splitter': { icon: Scissors, color: 'orange' },
  'text-joiner': { icon: FilePlus2, color: 'indigo' },
  'email-extractor': { icon: Mail, color: 'sky' },
  'keyword-extractor': { icon: Key, color: 'emerald' },
  'random-text-generator': { icon: Shuffle, color: 'purple' },
  'qr-generator': { icon: QrCode, color: 'violet' },
};

// Fallbacks by normalized category
const CATEGORY_FALLBACK_CONFIGS: Record<string, { icon: LucideIcon; color: string }> = {
  'image': { icon: Image, color: 'purple' },
  'pdf': { icon: FileText, color: 'rose' },
  'document': { icon: FileText, color: 'rose' },
  'business': { icon: Briefcase, color: 'emerald' },
  'career': { icon: Award, color: 'blue' },
  'developer': { icon: Code2, color: 'indigo' },
  'design': { icon: Palette, color: 'pink' },
  'text': { icon: Type, color: 'sky' },
  'video': { icon: Video, color: 'rose' },
  'audio': { icon: Music, color: 'violet' },
  'security': { icon: ShieldCheck, color: 'emerald' },
  'health': { icon: HeartPulse, color: 'rose' },
  'creator': { icon: Sparkles, color: 'pink' },
  'social': { icon: Sparkles, color: 'sky' },
  'government': { icon: Landmark, color: 'emerald' },
  'generator': { icon: QrCode, color: 'violet' },
  'prompt': { icon: Bot, color: 'emerald' }
};

const SIZE_MAP = {
  sm: { container: 'w-8 h-8 rounded-lg', icon: 'w-4 h-4' },
  md: { container: 'w-10 h-10 rounded-xl', icon: 'w-5 h-5' },
  lg: { container: 'w-12 h-12 rounded-2xl', icon: 'w-6 h-6' },
  xl: { container: 'w-14 h-14 rounded-2xl', icon: 'w-7 h-7' },
  '2xl': { container: 'w-16 h-16 rounded-3xl', icon: 'w-8 h-8' }
};

export const ToolIcon: React.FC<ToolIconProps> = ({
  toolId,
  category,
  className = '',
  iconClassName = '',
  size = 'md',
  showBackground = true
}) => {
  let selectedIcon: LucideIcon | null = null;
  let selectedColor = 'indigo';

  if (toolId && TOOL_CONFIGS[toolId]) {
    selectedIcon = TOOL_CONFIGS[toolId].icon;
    selectedColor = TOOL_CONFIGS[toolId].color;
  } else if (category) {
    const cleanCat = category.replace(/[^a-zA-Z]/g, '').toLowerCase();
    for (const [key, conf] of Object.entries(CATEGORY_FALLBACK_CONFIGS)) {
      if (cleanCat.includes(key)) {
        selectedIcon = conf.icon;
        selectedColor = conf.color;
        break;
      }
    }
  }

  // Keyword heuristic fallback if still not matched
  if (!selectedIcon && toolId) {
    const id = toolId.toLowerCase();
    if (id.includes('pdf')) { selectedIcon = FileText; selectedColor = 'rose'; }
    else if (id.includes('image') || id.includes('photo')) { selectedIcon = Image; selectedColor = 'purple'; }
    else if (id.includes('calc') || id.includes('tax') || id.includes('loan')) { selectedIcon = Calculator; selectedColor = 'emerald'; }
    else if (id.includes('video')) { selectedIcon = Video; selectedColor = 'rose'; }
    else if (id.includes('audio') || id.includes('music')) { selectedIcon = Music; selectedColor = 'violet'; }
    else if (id.includes('qr')) { selectedIcon = QrCode; selectedColor = 'violet'; }
    else if (id.includes('code') || id.includes('json') || id.includes('css')) { selectedIcon = Code2; selectedColor = 'indigo'; }
    else if (id.includes('text') || id.includes('word')) { selectedIcon = Type; selectedColor = 'sky'; }
    else if (id.includes('job') || id.includes('resume')) { selectedIcon = Briefcase; selectedColor = 'blue'; }
    else { selectedIcon = Sparkles; selectedColor = 'indigo'; }
  }

  if (!selectedIcon) {
    selectedIcon = Sparkles;
    selectedColor = 'indigo';
  }

  const colorStyle = COLOR_STYLES[selectedColor] || COLOR_STYLES.indigo;
  const dimensions = SIZE_MAP[size];
  const IconComp = selectedIcon;

  if (!showBackground) {
    return (
      <IconComp
        className={`${dimensions.icon} ${colorStyle.textColor} ${iconClassName}`}
        strokeWidth={2.25}
        aria-hidden="true"
      />
    );
  }

  return (
    <div
      className={`inline-flex items-center justify-center shrink-0 border shadow-xs transition-all duration-200 ${dimensions.container} ${colorStyle.bgLight} ${colorStyle.bgDark} ${colorStyle.borderColor} ${className}`}
    >
      <IconComp
        className={`${dimensions.icon} ${colorStyle.textColor} ${iconClassName}`}
        strokeWidth={2.25}
        aria-hidden="true"
      />
    </div>
  );
};
